name: Publish Docker image

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: vars
        run: echo "VER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Lowercase owner
        id: owner
        run: echo "NAME=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.owner.outputs.NAME }}/lib-version:latest
            ghcr.io/${{ steps.owner.outputs.NAME }}/lib-version:${{ steps.vars.outputs.VER }}
          build-args: |
            VERSION=${{ steps.vars.outputs.VER }}
            GITHUB_REPOSITORY=${{ github.repository }}

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-pre') }}
          body: |
            ## Docker images

            - `ghcr.io/${{ steps.owner.outputs.NAME }}/lib-version:${{ steps.vars.outputs.VER }}`
            - `ghcr.io/${{ steps.owner.outputs.NAME }}/lib-version:latest`
