name: Release Python Package to GitHub Packages

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v0.2.2)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version tag
        id: version
        run: |
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Convert repository owner to lowercase
        id: lowercase
        run: |
          echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Configure .pypirc for GitHub Packages
        run: |
          echo "[distutils]" > ~/.pypirc
          echo "index-servers =" >> ~/.pypirc
          echo "  github" >> ~/.pypirc
          echo "" >> ~/.pypirc
          echo "[github]" >> ~/.pypirc
          echo "repository = https://npm.pkg.github.com" >> ~/.pypirc
          echo "username = ${{ github.actor }}" >> ~/.pypirc
          echo "password = ${{ secrets.GH_PAT }}" >> ~/.pypirc

      - name: Publish to GitHub Packages
        run: |
          python -m twine upload \
            --repository github \
            --verbose \
            dist/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_PAT }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-pre') }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Python Package

            - `@${{ steps.lowercase.outputs.owner }}/lib_version:${{ steps.version.outputs.version }}` published to GitHub Packages

            ## Installation

            ```bash
            pip install lib_version==${{ steps.version.outputs.version }} --index-url https://npm.pkg.github.com/@${{ steps.lowercase.outputs.owner }}