name: Publish Python Package to GitHub Packages

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v0.2.1)

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version tag
        id: version
        run: |
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to GitHub Packages
        env:
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.PAT_GITHUB_TOKEN }}
        run: |
          python -m twine upload \
            --repository-url https://npm.pkg.github.com/@${{ github.repository_owner }} \
            dist/* \
            --verbose

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.PAT_GITHUB_TOKEN }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-pre') }}
          name: Release ${{ github.ref_name }}
          body: |

            - `lib_version@${{ steps.version.outputs.version }}` published to GitHub Packages

            ```bash
            pip install lib_version==${{ steps.version.outputs.version }} --index-url https://npm.pkg.github.com/@${{ github.repository_owner }}