name: Build & publish lib-version

on:
  push:                                   
    branches: [ "main" ]   
    tags:     [ 'v*.*.*' ]                   

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build wheel
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypitoken }}
